seed: 42
model: resnet18
num_classes: 2
input_size: 224
batch_size: 8
epochs: 40
lr: 3e-4
output_dir: outputs/cataract_resnet18_finetune

strategy: finetune        # standard | finetune | semisupervised | weakly | fewshot
strategy_kwargs:
  freeze_epochs: 5

data:
  train_images: data/cataract/train/images
  train_ann:    data/cataract/train/annotations.json
  val_images:   data/cataract/valid/images
  val_ann:      data/cataract/valid/annotations.json
  test_images:  data/cataract/test/images
  test_ann:     data/cataract/test/annotations.json
